apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-event-reader
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-cluster-events
subjects:
- kind: ServiceAccount
  name: aiops-gather
  namespace: aiops
roleRef:
  kind: ClusterRole
  name: cluster-event-reader
  apiGroup: rbac.authorization.k8s.io
